```{r}
library(tidyverse)
```

```{r}
library("mocdata")
```

```{r}
get_moc_price <- function(product_id,
                          from_date = "2021-01-01",
                          to_date = Sys.Date(),
                          meta = FALSE
                         ) {
  # initiate get object
  res <- httr::GET(
    "https://dataapi.moc.go.th/gis-product-prices?",
    query = list(
      product_id = product_id,
      from_date = from_date,
      to_date = to_date
    )
  )

  # transform from json to list
  res <- res %>%
    httr::content("text") %>%
    jsonlite::fromJSON()

  # create data frame
  data <- res$price_list %>%
    dplyr::mutate(
      product_id = res$product_id,
      date = as.Date(date),
      prive_avg = rowMeans(dplyr::across(price_min:price_max), na.rm = TRUE),
      unit = res$unit
    ) %>%
    dplyr::select(date, product_id, everything())

  # retrive metadata
  if (meta == TRUE) {
    meta <- res
    meta$price_list <- NULL
    meta$price_min_avg <- NULL
    meta$price_max_avg <- NULL
    attr(data, "meta") <- meta
  }

  return(data)
}
```

```{r}
ref_agproducts %>%
  filter(grepl("R11002", product_id))
```

```{r}
x <- get_moc_price("P16011", from_date = "2020-01-01", meta = FALSE)
```

```{r}
x
# attr(x, 'meta')
```

```{r}
get_moc_data <- function(query) {
  # initiate get object
  res <- httr::GET(
    "https://dataapi.moc.go.th/cpig-indexes?",
    query = query
  )

  # transform from json to list
  res <- res %>%
    httr::content("text") %>%
    jsonlite::fromJSON()
  
  return(res)
}
```

```{r}
query <- list(
  region_id = 2
)

get_moc_data(query)
```

```{r}
box::use(ggplot2[...])
```

```{r}

```
